#!/bin/sh
set -e
SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd "$SCRIPT_DIR/.." 
scripts/cargo run -- --help > /tmp/help.txt
man man/ned.1 > /tmp/man.txt
#ned '\s' -r '' /tmp/help.txt /tmp/man.txt
git diff --color-words=. -w /tmp/help.txt /tmp/man.txt
