[licenses]
unused-allowed-license = "deny"
unused-license-exception = "deny"
allow = ["Apache-2.0", "ISC", "MIT"]
exceptions = [{ name = "ned", allow = ["GPL-3.0-or-later"] }]
confidence-threshold = 0.8
