#!/bin/sh
set -e
SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd "$SCRIPT_DIR/.."
cargo build --release --target x86_64-unknown-linux-musl || exit 1
tar czf artifacts/ned.64-bit.musl.linux.tar.gz -C target/x86_64-unknown-linux-musl/release ned
