name: CI

on:
  push:
#   pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-lint-test:
    name: Build, Lint, Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      CARGO_TERM_COLOR: ${{ matrix.os == 'windows-latest' && 'never' || 'always' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Format Markdown
        if: runner.os == 'Linux'
        run: just format_markdown

      - name: Format Rust
        if: runner.os == 'Linux'
        run: just format_rust

      - name: Lint Markdown
        if: runner.os == 'Linux'
        run: just lint_markdown

      - name: Lint Rust
        if: runner.os == 'Linux'
        run: just lint_rust

      - name: Build Debug
        run: just build

      - name: Test Debug
        run: just test

      - name: Build Release
        run: just build --release

      - name: Test Release
        run: just test --release

  cargo-deny:
    name: Check Dependency Policy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-deny Package
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny

      - name: Run cargo-deny check
        run: |
          cargo deny check

  msrv:
    name: Minimum Supported Rust Version Build, Lint, Test (ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Rust (MSRV)
        uses: dtolnay/rust-toolchain@1.85.0

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build (MSRV)
        run: cargo build --all-targets

      - name: Lint (MSRV)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test (MSRV)
        run: cargo test

#   man-compare:
#     name: man/compare flag drift check
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Install just
#         uses: taiki-e/install-action@v2
#         with:
#           tool: just

#       - name: Run comparison via just
#         run: just man-compare
